/**
 * Bundled database assets — GENERATED by `npm run ingest`.
 *
 * Metro resolves `require()` at build time, so these paths have to be literals;
 * they cannot be built from an id at runtime. That is the only reason this is
 * separate from the registry in `@/bible/translations.ts`.
 */

export const TRANSLATION_ASSETS: Readonly<Record<string, number>> = {
  bsb: require('@/assets/bibles/bsb.db'),
  kjv: require('@/assets/bibles/kjv.db'),
  web: require('@/assets/bibles/web.db'),
};
