/**
 * The translations bundled in the app — GENERATED by `npm run ingest`.
 *
 * Read back out of the databases themselves, so this cannot drift from what is
 * actually shipped. Each translation is its own file in `assets/bibles/`; they
 * are never merged. Progress is stored as verse ids, so which one a person
 * reads is a display preference and nothing more — a circle reading three
 * different translations still shares one progress bar.
 */

export type BundledTranslation = {
  readonly id: string;
  readonly name: string;
  readonly abbreviation: string;
  readonly language: string;
  readonly licence: string;
  readonly verseCount: number;
  readonly noteCount: number;
  /** True when this translation marks the words of Jesus for red-letter reading. */
  readonly redLetter: boolean;
  /**
   * Short content hash of the bundled file. expo-sqlite copies an asset into
   * local storage once and reuses that copy forever, so a device holding an
   * older ingest would never see a correction. The app compares this against
   * what it last extracted and forces an overwrite when they differ.
   */
  readonly stamp: string;
};

export const TRANSLATIONS: readonly BundledTranslation[] = [
  {
    id: 'bsb',
    name: 'Berean Standard Bible',
    abbreviation: 'BSB',
    language: 'English',
    licence: 'Public Domain',
    verseCount: 31086,
    noteCount: 4808,
    redLetter: false,
    stamp: '6adccde4c3e9',
  },
  {
    id: 'kjv',
    name: 'King James Version',
    abbreviation: 'KJV',
    language: 'English',
    licence: 'Public Domain',
    verseCount: 31102,
    noteCount: 6959,
    redLetter: true,
    stamp: 'b01e777c5d37',
  },
  {
    id: 'web',
    name: 'World English Bible',
    abbreviation: 'WEB',
    language: 'English',
    licence: 'Public Domain',
    verseCount: 31103,
    noteCount: 1228,
    redLetter: true,
    stamp: '2575c5f6d79d',
  },
];

/** What a reader gets before they have chosen anything. */
export const DEFAULT_TRANSLATION_ID = 'web';

export function getTranslation(id: string): BundledTranslation | undefined {
  return TRANSLATIONS.find((t) => t.id === id);
}

/** The chosen translation, falling back when a stored id is no longer bundled. */
export function translationOrDefault(id: string | null | undefined): BundledTranslation {
  return (
    (id ? getTranslation(id) : undefined) ??
    getTranslation(DEFAULT_TRANSLATION_ID) ??
    TRANSLATIONS[0]
  );
}
