/**
 * Real verse counts, and everything that needs them.
 *
 * `verse-id.ts` deliberately works without this file: because no chapter holds
 * more than 176 verses, `999` is a safe open upper bound, so spans for chapters
 * and books can be built with no versification data at all. That is enough to
 * store progress, but not to measure it. Answering "how much of Luke is left?"
 * or "which chapter comes next?" needs to know that Luke 1 has 80 verses.
 *
 * The table lives in `versification-data.ts` and is generated by
 * `npm run ingest`. Everything here is built on one idea: every verse in the
 * canon has an **ordinal**, its 0-based index from Genesis 1:1. Counting the
 * verses in a range is then subtraction, whatever the range spans.
 *
 * A note on translations. Verse numbering is not universal — our table comes
 * from the World English Bible, which places the Romans doxology at the end of
 * chapter 14 where the Textus Receptus puts it at the end of chapter 16, so
 * Romans 14 and 16 are numbered differently there than in the KJV. Everywhere
 * else the two agree exactly. Ranges are still stored as ids and still mean the
 * same thing; only the count of verses inside those two chapters shifts. This
 * is why the ingestion script refuses to overwrite the table without being
 * asked twice.
 */

import { FIRST_BOOK, LAST_BOOK, getBook } from './canon.ts';
import { LAST_VERSE, VERSIFICATION_SOURCE, VERSIFICATION_TOTAL } from './versification-data.ts';
import {
  fromVerseId,
  makeRange,
  normaliseRanges,
  toVerseId,
  type VerseId,
  type VerseRange,
} from './verse-id.ts';

export { VERSIFICATION_SOURCE };

/** Every verse in the canon, under this versification. */
export const TOTAL_VERSES = VERSIFICATION_TOTAL;

/**
 * Verses in the canon before each chapter, laid out the same way as
 * `LAST_VERSE`. Turns a book and chapter into an ordinal without any counting.
 */
const CHAPTER_OFFSET: readonly (readonly number[])[] = (() => {
  const table: number[][] = [[]];
  let running = 0;
  for (let book = FIRST_BOOK; book <= LAST_BOOK; book++) {
    const chapters = LAST_VERSE[book] ?? [];
    const offsets: number[] = [];
    for (const last of chapters) {
      offsets.push(running);
      running += last;
    }
    table.push(offsets);
  }
  return table;
})();

/** The highest verse number in a chapter, or 0 if there is no such chapter. */
export function lastVerse(book: number, chapter: number): number {
  return LAST_VERSE[book]?.[chapter - 1] ?? 0;
}

/** The highest verse number of each chapter in a book, indexed from chapter 1. */
export function verseCounts(book: number): readonly number[] {
  return LAST_VERSE[book] ?? [];
}

/** Every verse in a book. */
export function bookVerseTotal(book: number): number {
  return verseCounts(book).reduce((sum, n) => sum + n, 0);
}

/** The id of a chapter's last verse — the real one, not the `999` upper bound. */
export function lastVerseId(book: number, chapter: number): VerseId | undefined {
  const last = lastVerse(book, chapter);
  return last === 0 ? undefined : toVerseId(book, chapter, last);
}

/**
 * Pull a verse id onto a verse that exists, so the `999` upper bounds that
 * `chapterSpan` and `bookSpan` produce can be measured. Chapters and verses are
 * clamped into range; an id outside the canon has nothing to clamp to.
 */
export function clampVerseId(id: VerseId): VerseId | undefined {
  const { book, chapter, verse } = fromVerseId(id);
  const chapters = LAST_VERSE[book];
  if (!chapters || chapters.length === 0) return undefined;

  const boundedChapter = Math.min(Math.max(chapter, 1), chapters.length);
  const last = chapters[boundedChapter - 1];
  return toVerseId(book, boundedChapter, Math.min(Math.max(verse, 1), last));
}

/**
 * A verse's 0-based index from Genesis 1:1, or -1 for an id outside the canon.
 * Ids are clamped first, so the open upper bounds are handled.
 */
export function verseOrdinal(id: VerseId): number {
  const clamped = clampVerseId(id);
  if (clamped === undefined) return -1;
  const { book, chapter, verse } = fromVerseId(clamped);
  return CHAPTER_OFFSET[book][chapter - 1] + verse - 1;
}

/**
 * The first verse that exists at or after `id`, stepping into the next chapter
 * or book when `id` points past the end of its own.
 *
 * This is what `clampVerseId` cannot do: it pulls everything back into the
 * chapter it was given, which is right for the end of a range and wrong for the
 * start. Subtracting a chapter that has been read from a padded span leaves
 * something like Psalm 1:7-999 — a range holding no verses at all, since Psalm
 * 1 ends at 6. Clamping both ends of that lands them both on verse 6 and counts
 * one verse that was never there.
 */
export function firstVerseFrom(id: VerseId): VerseId | undefined {
  const { book, chapter, verse } = fromVerseId(id);
  if (book > LAST_BOOK) return undefined;

  for (let b = Math.max(book, FIRST_BOOK); b <= LAST_BOOK; b++) {
    const chapters = LAST_VERSE[b] ?? [];
    const from = b === book ? Math.max(chapter, 1) : 1;
    for (let c = from; c <= chapters.length; c++) {
      const last = chapters[c - 1] ?? 0;
      if (last === 0) continue;
      const wanted = b === book && c === chapter ? Math.max(verse, 1) : 1;
      if (wanted <= last) return toVerseId(b, c, wanted);
    }
  }
  return undefined;
}

/** The inverse of `verseOrdinal`. */
export function verseIdAtOrdinal(ordinal: number): VerseId | undefined {
  if (!Number.isInteger(ordinal) || ordinal < 0 || ordinal >= TOTAL_VERSES) return undefined;

  for (let book = FIRST_BOOK; book <= LAST_BOOK; book++) {
    const offsets = CHAPTER_OFFSET[book];
    const chapters = LAST_VERSE[book];
    const past = offsets[0] + bookVerseTotal(book);
    if (ordinal >= past) continue;

    // Binary search would be quicker, but a book holds at most 150 chapters.
    for (let chapter = chapters.length; chapter >= 1; chapter--) {
      const offset = offsets[chapter - 1];
      if (ordinal >= offset) return toVerseId(book, chapter, ordinal - offset + 1);
    }
  }
  return undefined;
}

/** The last verse that exists at or before `id`, stepping back if need be. */
export function lastVerseUpTo(id: VerseId): VerseId | undefined {
  const { book, chapter, verse } = fromVerseId(id);
  if (book < FIRST_BOOK) return undefined;

  for (let b = Math.min(book, LAST_BOOK); b >= FIRST_BOOK; b--) {
    const chapters = LAST_VERSE[b] ?? [];
    const from = b === book ? Math.min(chapter, chapters.length) : chapters.length;
    for (let c = from; c >= 1; c--) {
      const last = chapters[c - 1] ?? 0;
      if (last === 0) continue;
      const wanted = b === book && c === chapter ? Math.min(verse, last) : last;
      if (wanted >= 1) return toVerseId(b, c, wanted);
    }
  }
  return undefined;
}

/** A chapter's true span, first verse to last. */
export function chapterRange(book: number, chapter: number): VerseRange | undefined {
  const end = lastVerseId(book, chapter);
  return end === undefined ? undefined : { start: toVerseId(book, chapter, 1), end };
}

/** A book's true span, Genesis 1:1 style through its final verse. */
export function bookRange(book: number): VerseRange | undefined {
  const chapters = verseCounts(book);
  if (chapters.length === 0) return undefined;
  return makeRange(toVerseId(book, 1, 1), toVerseId(book, chapters.length, chapters.at(-1)!));
}

/** The whole canon, measured rather than bounded. */
export function canonRange(): VerseRange {
  return makeRange(toVerseId(FIRST_BOOK, 1, 1), bookRange(LAST_BOOK)!.end);
}

/**
 * How many verses a set of ranges actually covers. Overlapping ranges are
 * merged first, so this is the size of the union rather than a sum — which is
 * what makes it the right number for a progress bar.
 */
export function countVerses(ranges: readonly VerseRange[]): number {
  let total = 0;
  for (const range of normaliseRanges(ranges)) {
    // Snap outward-in: the start forward onto a verse that exists, the end
    // backward onto one. A range holding no real verses collapses to nothing.
    const from = firstVerseFrom(range.start);
    const to = lastVerseUpTo(range.end);
    if (from === undefined || to === undefined || from > to) continue;

    const start = verseOrdinal(from);
    const end = verseOrdinal(to);
    if (start < 0 || end < 0 || end < start) continue;
    total += end - start + 1;
  }
  return total;
}

/** What fraction of `target` the ranges in `covered` account for, 0 to 1. */
export function progressThrough(
  target: readonly VerseRange[],
  covered: readonly VerseRange[],
): number {
  const whole = countVerses(target);
  if (whole === 0) return 0;
  const done = countVerses(intersect(target, covered));
  return done / whole;
}

/** The overlap of two range sets, kept private so `countVerses` stays the API. */
function intersect(a: readonly VerseRange[], b: readonly VerseRange[]): VerseRange[] {
  const left = normaliseRanges(a);
  const right = normaliseRanges(b);
  const out: VerseRange[] = [];
  let i = 0;
  let j = 0;
  while (i < left.length && j < right.length) {
    const start = Math.max(left[i].start, right[j].start);
    const end = Math.min(left[i].end, right[j].end);
    if (start <= end) out.push({ start, end });
    if (left[i].end < right[j].end) i++;
    else j++;
  }
  return out;
}

export type ChapterRef = { readonly book: number; readonly chapter: number };

/** The next chapter, stepping over the book boundary. Undefined after Revelation. */
export function nextChapter(book: number, chapter: number): ChapterRef | undefined {
  if (lastVerse(book, chapter) === 0) return undefined;
  if (chapter < verseCounts(book).length) return { book, chapter: chapter + 1 };
  return book < LAST_BOOK ? { book: book + 1, chapter: 1 } : undefined;
}

/** The previous chapter. Undefined before Genesis 1. */
export function previousChapter(book: number, chapter: number): ChapterRef | undefined {
  if (lastVerse(book, chapter) === 0) return undefined;
  if (chapter > 1) return { book, chapter: chapter - 1 };
  return book > FIRST_BOOK ? { book: book - 1, chapter: verseCounts(book - 1).length } : undefined;
}

/**
 * Check the generated table against `canon.ts`. Cheap enough to run in a test,
 * and the thing most worth knowing after a re-ingest.
 */
export function versificationProblems(): string[] {
  const problems: string[] = [];
  for (let book = FIRST_BOOK; book <= LAST_BOOK; book++) {
    const meta = getBook(book);
    const chapters = verseCounts(book);
    if (!meta) {
      problems.push(`book ${book} is missing from canon.ts`);
      continue;
    }
    if (chapters.length !== meta.chapters) {
      problems.push(`${meta.name}: canon.ts says ${meta.chapters} chapters, table has ${chapters.length}`);
    }
    chapters.forEach((last, index) => {
      if (!Number.isInteger(last) || last < 1) {
        problems.push(`${meta.name} ${index + 1} has no verses`);
      }
    });
  }
  return problems;
}
